// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	models "ourgym/models"

	mock "github.com/stretchr/testify/mock"
)

// MeRepository is an autogenerated mock type for the MeRepository type
type MeRepository struct {
	mock.Mock
}

// GetTransactionByID provides a mock function with given fields: userID
func (_m *MeRepository) GetTransactionByID(userID string) []models.Transaction {
	ret := _m.Called(userID)

	var r0 []models.Transaction
	if rf, ok := ret.Get(0).(func(string) []models.Transaction); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Transaction)
		}
	}

	return r0
}

type mockConstructorTestingTNewMeRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMeRepository creates a new instance of MeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMeRepository(t mockConstructorTestingTNewMeRepository) *MeRepository {
	mock := &MeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
