name: CD DEV
on:
  push:
    branches:
      - "development"
      
jobs:
  testing:
    runs-on: ubuntu-latest
    name: "testing"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: run unit test
        run: go test -v ./...

  deploy:
    runs-on: ubuntu-latest
    name: "deploy app"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: andianugrahaqsa/capstone-alta:latest

      - name: update aws instance
        uses: appleboy/ssh-action@master
        with:
          host: ec2-54-65-17-32.ap-northeast-1.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.AWS_KEY }}
          port: 22
          script: |
            sudo docker stop capstone-app
            sudo docker container rm capstone-app
            sudo docker rmi andianugrahaqsa/capstone-alta:latest
            sudo docker pull andianugrahaqsa/capstone-alta:latest
            sudo docker run -itd -p 80:8080 --name capstone-app andianugrahaqsa/capstone-alta:latest